console.log('Hello John!')
console.log('Lorem ipsum dolor sit amet, consectetur adipiscing elit.')
console.log('Lorem ipsum dolor sit amet, consectetur adipiscing elit.')
console.log('Lorem ipsum dolor sit amet, consectetur adipiscing elit.')
console.log('Lorem ipsum dolor sit amet, consectetur adipiscing elit.')
