name: Release

on:
  push:
    branches: [ feature/push_test ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  REACT_APP_BRIDGE: ${{ secrets.REACT_APP_BRIDGE }}
  REACT_APP_STORAGE: ${{ secrets.REACT_APP_STORAGE }}
  REACT_APP_MORALIS_PROXY_URL: ${{ secrets.REACT_APP_MORALIS_PROXY_URL }}
  REACT_APP_CRYPTO_TRADING_WIDGET_URL: ${{ secrets.REACT_APP_CRYPTO_TRADING_WIDGET_URL }}
  
jobs:
  release:
      runs-on: ubuntu-22.04
      steps:
        - uses: actions/checkout@v2
        - name: Set up Node.js version
          uses: actions/setup-node@v1
          with:
            node-version: '18.16.0'

        - name: Initialize Git user
          run: |
            git config user.name "${GITHUB_ACTOR}"
            git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        - name: check env
          run: |
            npm ci
            npm run release
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
