name: Release

on:
  push:
    branches: [ feature/push_test ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  release:
      runs-on: ubuntu-22.04
      steps:
        - uses: actions/checkout@v2
        - name: Set up Node.js version
          uses: actions/setup-node@v1
          with:
            node-version: '18.16.0'

        - name: Initialize Git user
          run: |
            git config user.name "${GITHUB_ACTOR}"
            git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        - name: install dependencies and release
          run: |
            npm ci
            npm run release
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}